/**
 * Flattens the raw nested source JSON (Province -> District -> Sector ->
 * Cell -> Village) into five normalized, flat arrays under src/data/,
 * each row carrying an explicit parent foreign key.
 *
 * Usage: npm run generate:data -- <path-to-raw-source.json>
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

interface RawVillage {
  id: number;
  name: string;
  cell_id: number;
}
interface RawCell {
  id: number;
  name: string;
  sector_id: number;
  villages?: RawVillage[];
}
interface RawSector {
  id: number;
  name: string;
  district_id: number;
  cells?: RawCell[];
}
interface RawDistrict {
  id: number;
  name: string;
  province_id: number;
  sectors?: RawSector[];
}
interface RawProvince {
  id: number;
  name: string;
  districts?: RawDistrict[];
}

const inputPath = process.argv[2];
if (!inputPath) {
  console.error("Usage: npm run generate:data -- <path-to-raw-source.json>");
  process.exit(1);
}

const raw: RawProvince[] = JSON.parse(readFileSync(resolve(inputPath), "utf-8"));

const provinces: { id: number; name: string }[] = [];
const districts: { id: number; name: string; provinceId: number }[] = [];
const sectors: { id: number; name: string; districtId: number }[] = [];
const cells: { id: number; name: string; sectorId: number }[] = [];
const villages: { id: number; name: string; cellId: number }[] = [];

const ids = {
  province: new Set<number>(),
  district: new Set<number>(),
  sector: new Set<number>(),
  cell: new Set<number>(),
  village: new Set<number>(),
};

function assertUnique(set: Set<number>, id: number, level: string): void {
  if (set.has(id)) {
    throw new Error(`Duplicate ${level} id found in source data: ${id}`);
  }
  set.add(id);
}

/**
 * Compares the source's own FK field against the id of the parent we
 * actually found it nested under, and logs (does not throw) on mismatch.
 * The nesting is treated as ground truth; the FK field is just checked
 * for data-quality visibility.
 */
function warnIfFkDisagrees(
  level: string,
  childId: number,
  fkFieldName: string,
  fkFieldValue: unknown,
  actualParentId: number,
): void {
  if (fkFieldValue !== actualParentId) {
    console.warn(
      `[warn] ${level} id=${childId}: source field "${fkFieldName}"=${JSON.stringify(
        fkFieldValue,
      )} does not match actual nesting parent id=${actualParentId}. Using ${actualParentId} (from nesting).`,
    );
  }
}

for (const p of raw) {
  assertUnique(ids.province, p.id, "province");
  provinces.push({ id: p.id, name: p.name });

  for (const d of p.districts ?? []) {
    assertUnique(ids.district, d.id, "district");
    warnIfFkDisagrees("district", d.id, "province_id", d.province_id, p.id);
    districts.push({ id: d.id, name: d.name, provinceId: p.id });

    for (const s of d.sectors ?? []) {
      assertUnique(ids.sector, s.id, "sector");
      warnIfFkDisagrees("sector", s.id, "district_id", s.district_id, d.id);
      sectors.push({ id: s.id, name: s.name, districtId: d.id });

      for (const c of s.cells ?? []) {
        assertUnique(ids.cell, c.id, "cell");
        warnIfFkDisagrees("cell", c.id, "sector_id", c.sector_id, s.id);
        cells.push({ id: c.id, name: c.name, sectorId: s.id });

        for (const v of c.villages ?? []) {
          assertUnique(ids.village, v.id, "village");
          warnIfFkDisagrees("village", v.id, "cell_id", v.cell_id, c.id);
          villages.push({ id: v.id, name: v.name, cellId: c.id });
        }
      }
    }
  }
}

function writeDataFile(name: string, type: string, rows: readonly { id: number }[]): void {
  const sorted = [...rows].sort((a, b) => a.id - b.id);
  const body = sorted.map((row) => `  ${JSON.stringify(row)},`).join("\n");
  const content = `// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
// Generated by scripts/generate-data.ts from the raw source JSON.
// Run: npm run generate:data -- <path-to-raw-source.json>

import type { ${type} } from "../types.js";

export const ${name}: readonly ${type}[] = [
${body}
];
`;
  writeFileSync(resolve(`src/data/${name}.ts`), content);
}

writeDataFile("provinces", "Province", provinces);
writeDataFile("districts", "District", districts);
writeDataFile("sectors", "Sector", sectors);
writeDataFile("cells", "Cell", cells);
writeDataFile("villages", "Village", villages);

console.log(
  `Generated ${provinces.length} provinces, ${districts.length} districts, ` +
    `${sectors.length} sectors, ${cells.length} cells, ${villages.length} villages.`,
);
