// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
// Generated by scripts/generate-data.ts from the raw source JSON.
// Run: npm run generate:data -- <path-to-raw-source.json>

import type { District } from "../types.js";

export const districts: readonly District[] = [
  {"id":101,"name":"Nyarugenge","provinceId":1},
  {"id":102,"name":"Gasabo","provinceId":1},
  {"id":103,"name":"Kicukiro","provinceId":1},
  {"id":201,"name":"Nyanza","provinceId":2},
  {"id":202,"name":"Gisagara","provinceId":2},
  {"id":203,"name":"Nyaruguru","provinceId":2},
  {"id":204,"name":"Huye","provinceId":2},
  {"id":205,"name":"Nyamagabe","provinceId":2},
  {"id":206,"name":"Ruhango","provinceId":2},
  {"id":207,"name":"Muhanga","provinceId":2},
  {"id":208,"name":"Kamonyi","provinceId":2},
  {"id":301,"name":"Karongi","provinceId":3},
  {"id":302,"name":"Rutsiro","provinceId":3},
  {"id":303,"name":"Rubavu","provinceId":3},
  {"id":304,"name":"Nyabihu","provinceId":3},
  {"id":305,"name":"Ngororero","provinceId":3},
  {"id":306,"name":"Rusizi","provinceId":3},
  {"id":307,"name":"Nyamasheke","provinceId":3},
  {"id":401,"name":"Rulindo","provinceId":4},
  {"id":402,"name":"Gakenke","provinceId":4},
  {"id":403,"name":"Musanze","provinceId":4},
  {"id":404,"name":"Burera","provinceId":4},
  {"id":405,"name":"Gicumbi","provinceId":4},
  {"id":501,"name":"Rwamagana","provinceId":5},
  {"id":502,"name":"Nyagatare","provinceId":5},
  {"id":503,"name":"Gatsibo","provinceId":5},
  {"id":504,"name":"Kayonza","provinceId":5},
  {"id":505,"name":"Kirehe","provinceId":5},
  {"id":506,"name":"Ngoma","provinceId":5},
  {"id":507,"name":"Bugesera","provinceId":5},
];
