// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
// Generated by scripts/generate-data.ts from the raw source JSON.
// Run: npm run generate:data -- <path-to-raw-source.json>

import type { Province } from "../types.js";

export const provinces: readonly Province[] = [
  {"id":1,"name":"KIGALI"},
  {"id":2,"name":"SOUTH"},
  {"id":3,"name":"WEST"},
  {"id":4,"name":"NORTH"},
  {"id":5,"name":"EAST"},
];
